### ISSUE TITLE
Doesn't load almost every map anymore

### ISSUE THREAD

**Issue by HunterTheCapricorn** [njibhu/t3d#189]
Went to check this tool again after some years when I discovered it first but it seems to be stuck at loading, raising ram usage and then crash Chrome. 
Only one of the maps (the dev test one) can be loaded. 
I made sure to exclude all the power hungry options for faster loading too. 
I wonder if this tool is even still usable or abandoned by now.

**Comment by njibhu** [comment]
Was fixed with the v3.0.0 version
